backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

collections:
    - label: "Pages"
      name: "pages"
      files:
          - label: "Home Page"
            name: "home"
            file: "src/_data/home.json"
            fields:
                - label: Title
                  name: title
                  widget: string
                - label: "Focus Keyword"
                  name: "yoast_keyword"
                  widget: "string"
                - label: "Meta Description"
                  name: "description"
                  widget: "string"
                - label: "Content"
                  name: "content"
                  widget: "object"
                  fields:
                      - label: Intro
                        name: intro
                        widget: text
                      - label: IntroImage
                        name: introImage
                        widget: image
                        media_library:
                            config:
                                multiple: false

media_folder: "src/images/uploads"
public_folder: "/images/uploads"
