backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

collections:
    - label: "Pages"
      name: "pages"
      files:
          - label: "Home Page"
            name: "home"
            file: "src/_data/home.json"
            fields:
                - label: Title
                  name: title
                  widget: string
                - label: Intro
                  name: intro
                  widget: text
                - label: IntroImage
                  name: introImage
                  widget: image
                  media_library:
                      config:
                          multiple: false

media_folder: "images/uploads"
