backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - label: Global
    name: global
    files:
      - label: Site Data
        name: site_data
        file: src/_data/site.json
        fields:
          - label: Logo
            name: logo
            widget: image
            media_library:
              config:
                multiple: false
          - label: Logo Light
            name: logo_light
            widget: image
            media_library:
              config:
                multiple: false
          - label: Logo Dark
            name: logo_dark
            widget: image
            media_library:
              config:
                multiple: false

      - label: SEO Data
        name: seo_metadata
        file: src/_data/seo.json
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
          - label: URL
            name: url
            widget: string
            options:
              default: https://smartcoaching.netlify.com/
          - label: Author
            name: author
            widget: string
            options:
              default: Saurabh Dutta
          - label: Focus Keyword
            name: keywords
            widget: string
          - label: Image
            name: image
            widget: image
            media_library:
              config:
                multiple: false

  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      - label: Home Page
        name: home
        file: src/index.11tydata.yaml
        fields:
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Text
                name: text
                widget: markdown
              - label: Image
                name: image
                widget: image
                media_library:
                  config:
                    multiple: false
          - label: Forms
            name: forms
            widget: list
            allow_add: true
            fields:
              - label: Form ID
                name: form_id
              - label: Button Title
                name: button_title
                widget: string
              


media_folder: src/images/uploads
public_folder: /images/uploads
