backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - label: Global
    name: global
    files:
      - label: Site Data
        name: site_data
        file: src/_data/site.json
        fields:
          - label: Contact
            name: contact_number            
          - label: Logo
            name: logo
            widget: image
            media_library:
              config:
                multiple: false
          - label: Logo Light
            name: logo_light
            widget: image
            media_library:
              config:
                multiple: false
          - label: Logo Dark
            name: logo_dark
            widget: image
            media_library:
              config:
                multiple: false

      - label: SEO Data
        name: seo_metadata
        file: src/_data/seo.json
        fields:
          - label: Title
            name: title
          - label: Description
            name: description
            widget: text
          - label: URL
            name: url
            options:
              default: https://smartcoaching.netlify.com/
          - label: Author
            name: author
            options:
              default: Saurabh Dutta
          - label: Focus Keyword
            name: keywords
          - label: Image
            name: image
            widget: image
            media_library:
              config:
                multiple: false

  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      - label: Home Page
        name: home
        file: src/index.11tydata.yaml
        fields:
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Title
                name: title
              - label: Text
                name: text
                widget: markdown
              - label: Image
                name: image
                widget: image
                media_library:
                  config:
                    multiple: false
              - label: Notices
                name: notices
                widget: list                
                field: { label: Content, name: content, widget: string }
          - label: Forms
            name: forms
            widget: list            
            fields:
              - label: Button Title
                name: button_title
              - label: Form ID
                name: form_id
          - label: Features
            name: features
            widget: list
            fields:
              - label: Title
                name: title
              - label: Icon
                name: icon
                widget: image
                media_library:
                  config:
                    multiple: false
              - label: Description
                name: description
                widget: text
          - label: Faculties
            name: faculties
            widget: list
            fields:
              - label: Name
                name: name
              - label: Photo
                name: photo
                widget: image
                media_library:
                  config:
                    multiple: false              
              - label: Experience
                name: experience
              - label: Speciality
                name: speciality
              - label: Qualification
                name: qualification
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Name
                name: name
              - label: SubText
                name: subtext
                required: false
              - label: Content
                name: content
                widget: text
          - label: Gallery
            name: gallery
            widget: list
            field: { label: Image, name: image, widget: image }
          - label: Contact
            name: contact
            widget: object
            fields:
              - label: Email Address
                name: email_address              
              - label: Phone Numbers
                name: phone_numbers
                widget: list
                field: { label: mobile, name: mobile, widget: string }
              - label: Address
                name: address
                widget: markdown
              - label: Map
                name: map                            
          - label: Social Media link
            name: social_links
            widget: list
            fields:
              - label: Title
                name: title
              - label: Link
                name: link
                  
media_folder: src/images/uploads
public_folder: /images/uploads
